- hosts: all
  remote_user: root
  tasks:
    - name: remove the mariadb
      yum:
        name: mariadb
        state: absent

    - name: install mysql 1
      shell: "{{ item }}"
      with_items:
         - wget http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
         - yum localinstall -y mysql57-community-release-el7-11.noarch.rpm

    - name : install mysql 2
      yum:
        name: mysql-community-server
      async : 1000
      poll : 0
      register: mysql_install_result

    - name: 'check install result'
      async_status: jid={{ mysql_install_result.ansible_job_id }}
      register: job_mysql_install_result
      until: job_mysql_install_result.finished
      retries: 250

    - name: remove old /etc/my.cnf
      file:
        path: "/etc/my.cnf"
        state: absent

    - name: create my.cnf file
      file:
        path="/etc/{{ item }}"
        state=touch
      with_items:
        - my.cnf

    - name: set my.cnf
      blockinfile:
        path: /etc/my.cnf
        marker: ""
        block: |
            [mysql]
            default-character-set = utf8mb4
            [mysqld]
            max_connections = 500
            datadir = /var/lib/mysql
            socket = /var/lib/mysql/mysql.sock
            bind-address = 127.0.0.1
            symbolic-links=0
            log-error=/var/log/mysqld.log
            pid-file=/var/run/mysqld/mysqld.pid
            default-storage-engine = InnoDB
            collation-server = utf8mb4_unicode_520_ci
            init_connect = 'SET NAMES utf8mb4'
            character-set-server = utf8mb4
            lower_case_table_names = 1
            max_allowed_packet = 50M
            sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    - name: enable mysql
      shell: "{{ item }}"
      with_items:
         - systemctl enable mysqld.service
         - systemctl restart mysqld.service
