- hosts: all
  remote_user: root
  tasks:
    - name : ansible-test
      shell : sleep 30
      async : 1000
      poll : 0
      register: kevin_result

    - name: 'check ansible-test task polling results '
      async_status: jid={{ kevin_result.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 200
